language: python
python: 3.6.3
addons:
  apt_packages:
    - pandoc
script:
- python3 test.py
after_success:
- git config --global user.name "PythonSemVer (via TravisCI)"
- git config --global user.email "PythonSemVer@travis"
- pip3 install pandoc
- python3 setup.py install
- semantic-release publish
